apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: 308564447263.dkr.ecr.ap-south-1.amazonaws.com/netflix-clone:master-e022eff5f8faa23e9b969bf8f6e7a0e850b01c7c
          ports:
            - containerPort: 80
