apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: 308564447263.dkr.ecr.ap-south-1.amazonaws.com/netflix-prod:master-a47c6c76b021cae23a8785bae40dc24bc8b5c48b
          ports:
            - containerPort: 80
